title: "Friday Felt"
description: "Friday Night Poker Tour"
theme: just-the-docs
baseurl: "/fridayfelt" # Name of your repo
url: "https://mrwayneo.github.io"
search_enabled: true

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template

