source "https://rubygems.org"

gem "jekyll", "~> 4.2.2"
gem "just-the-docs", "0.12.0"
gem "jekyll-remote-theme", "~> 0.4.3"
gem "jekyll-seo-tag"
gem "webrick"

# Keeps local builds compatible with the Ruby version bundled with macOS..
gem "ffi", "1.15.5"
